#!/bin/bash

set -euo pipefail

. /etc/evalr/creds

coproc GAWK {
	gawk \
		-f /usr/libexec/evalr/main.awk \
		-v "IRC_NICKNAME=$IRC_NICKNAME" \
		-v "IRC_USERNAME=$IRC_USERNAME" \
		-v "IRC_PASSWORD=${IRC_PASSWORD:-}"
}

<&"${GAWK[0]}" openssl s_client -connect "$IRC_SERVER" -quiet >&"${GAWK[1]}"
